# Generated by Django 3.2.6 on 2021-10-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mitarbeiter_ID', models.CharField(max_length=200, primary_key=True)),
                ('Leistungsdatum', models.CharField(max_length=200)),
                ('Taetigkeit', models.CharField(max_length=200)),
                ('Kostenstelle', models.CharField(max_length=200)),
                ('Bundesland', models.CharField(max_length=200)),
            ],
        ),
    ]
