# Generated by Django 3.2.6 on 2021-10-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20211018_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausschreibungen',
            name='DatumNotifikation',
            field=models.CharField(max_length=200),
        ),
    ]
